"""initial schema

Revision ID: f6fc4fb5d9f2
Revises:
Create Date: 2026-03-23 15:52:25.202243
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6fc4fb5d9f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for trigram GIN indexes (search).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "presets",
        sa.Column("preset_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("toolsets", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("environment", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("tool_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("subagents", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("mcp_servers", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("preset_id", name=op.f("pk_presets")),
    )
    op.create_index(
        "ix_presets_is_default", "presets", ["is_default"], unique=True, postgresql_where=sa.text("is_default = true")
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("role", sa.String(), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("must_change_password", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("projects", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "api_keys",
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], name="fk_api_keys_user_id_users"),
        sa.PrimaryKeyConstraint("key_id", name=op.f("pk_api_keys")),
    )
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=True)
    op.create_index("ix_api_keys_user_id", "api_keys", ["user_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("default_preset_id", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], name="fk_conversations_user_id_users"),
        sa.PrimaryKeyConstraint("conversation_id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_summary_trgm",
        "conversations",
        ["summary"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"summary": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_conversations_title_trgm",
        "conversations",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("parent_session_id", sa.String(), nullable=True),
        sa.Column("project_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("status", sa.String(), server_default="created", nullable=False),
        sa.Column("run_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("session_type", sa.String(), server_default="agent", nullable=False),
        sa.Column("transport", sa.String(), server_default="sse", nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("spawned_by", sa.String(), nullable=True),
        sa.Column("preset_id", sa.String(), nullable=True),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final_message", sa.Text(), nullable=True),
        sa.Column("deferred_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("clock_timestamp()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.conversation_id"], name="fk_sessions_conversation_id"
        ),
        sa.ForeignKeyConstraint(["parent_session_id"], ["sessions.session_id"], name="fk_sessions_parent_session_id"),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_conversation_id", "sessions", ["conversation_id"], unique=False)
    op.create_index(
        "ix_sessions_final_message_trgm",
        "sessions",
        ["final_message"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"final_message": "gin_trgm_ops"},
    )
    op.create_index("ix_sessions_status", "sessions", ["status"], unique=False)
    op.create_table(
        "mailbox",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("source_session_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("subagent_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivered_to", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.conversation_id"], name="fk_mailbox_conversation_id"
        ),
        sa.ForeignKeyConstraint(["source_session_id"], ["sessions.session_id"], name="fk_mailbox_source_session_id"),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_mailbox")),
    )
    op.create_index("ix_mailbox_conversation_id", "mailbox", ["conversation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mailbox_conversation_id", table_name="mailbox")
    op.drop_table("mailbox")
    op.drop_index("ix_sessions_status", table_name="sessions")
    op.drop_index(
        "ix_sessions_final_message_trgm",
        table_name="sessions",
        postgresql_using="gin",
        postgresql_ops={"final_message": "gin_trgm_ops"},
    )
    op.drop_index("ix_sessions_conversation_id", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_conversations_user_id", table_name="conversations")
    op.drop_index(
        "ix_conversations_title_trgm",
        table_name="conversations",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_conversations_summary_trgm",
        table_name="conversations",
        postgresql_using="gin",
        postgresql_ops={"summary": "gin_trgm_ops"},
    )
    op.drop_table("conversations")
    op.drop_index("ix_api_keys_user_id", table_name="api_keys")
    op.drop_index("ix_api_keys_key_hash", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("workspaces")
    op.drop_table("users")
    op.drop_index("ix_presets_is_default", table_name="presets", postgresql_where=sa.text("is_default = true"))
    op.drop_table("presets")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
